triggers:
- envs: []
  last_enabled_at: 2024-02-06 17:15:41.800667
  name: green_taxi_etl_trigger
  pipeline_uuid: green_taxi_etl
  schedule_interval: 0 5 * * *
  schedule_type: time
  settings: null
  sla: null
  start_time: 2024-02-07 05:00:00
  status: active
  variables: {}
